Repository imobanco/bb-wrapper, pull requests merged in 2022-08, with the labels that each got.

#34 Erros de estorno para API de Pagamentos em Lote
  bb_wrapper/models/pagamentos.py
Labels: Urgência: Alta :stopwatch:, Importância: Alta :warning:

#37 Ajusta autenticação com a API BB
  .envrc
  .github/workflows/pypi.yml
  .github/workflows/tests.yml
  Makefile
  README.rst
  bb_wrapper/wrapper/bb.py
  bb_wrapper/wrapper/cobrancas.py
  bb_wrapper/wrapper/pagamento_lote.py
  bb_wrapper/wrapper/pix_cob.py
  examples/pix_cob/data/consultar_cobranca.json
  flake.nix
  poetry.lock
  pyproject.toml
  requirements-build.txt
  requirements-dev.txt
  requirements.txt
  setup.py
  tests/utils.py
  tests/wrapper/test_bb_base.py
  tests/wrapper/test_pagamentos.py
Labels: Tipo: Refatoração :recycle:

#45 Corrige url da API de produção de Lotes de Pagamento
  .github/workflows/pypi.yml
  .github/workflows/tests.yml
  bb_wrapper/wrapper/pagamento_lote.py
  tests/wrapper/test_pagamentos.py
Labels: Tipo: Hotfix :firefighter:, Urgência: Alta :stopwatch:, Importância: Alta :warning:
